/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new tenant with admin user */
        post: operations["registerTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with username and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenant/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tenant profile */
        get: operations["getTenantProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update tenant profile */
        patch: operations["updateTenantProfile"];
        trace?: never;
    };
    "/v1/tenant/ui-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set tenant default UI preferences (admin) */
        patch: operations["patchTenantUiPreferences"];
        trace?: never;
    };
    "/v1/me/ui-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Effective UI preferences for current user */
        get: operations["getUiPreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user UI preferences (overrides tenant defaults where allowed) */
        patch: operations["patchUserUiPreferences"];
        trace?: never;
    };
    "/v1/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List installed apps for current tenant and user */
        get: operations["listInstalledApps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenant/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all known apps with installation status for current tenant (admin) */
        get: operations["listTenantAppCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenant/apps/{appKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activate or deactivate an app for the current tenant (admin) */
        patch: operations["patchTenantAppStatus"];
        trace?: never;
    };
    "/v1/apps/{appKey}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get app manifest */
        get: operations["getAppManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/apps/{appKey}/settings/effective": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Merged app settings for current user */
        get: operations["getEffectiveAppSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenant/apps/{appKey}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tenant-wide app settings overrides */
        get: operations["getTenantAppSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update tenant app settings (admin only) */
        patch: operations["patchTenantAppSettings"];
        trace?: never;
    };
    "/v1/me/apps/{appKey}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User app settings overrides */
        get: operations["getUserAppSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user app settings */
        patch: operations["patchUserAppSettings"];
        trace?: never;
    };
    "/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTeams"];
        put?: never;
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteTeam"];
        options?: never;
        head?: never;
        patch: operations["updateTeam"];
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTenantUsers"];
        put?: never;
        post: operations["createTenantUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTenantUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateTenantUser"];
        trace?: never;
    };
    "/v1/case-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List case models */
        get: operations["listCaseModels"];
        put?: never;
        /** Create case model */
        post: operations["createCaseModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/case-models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCaseModel"];
        put?: never;
        post?: never;
        delete: operations["deleteCaseModel"];
        options?: never;
        head?: never;
        patch: operations["updateCaseModel"];
        trace?: never;
    };
    "/v1/case-models/{id}/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCaseModelAttributes"];
        put?: never;
        post: operations["createCaseModelAttribute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/case-models/{id}/task-model-exclusions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCaseModelTaskModelExclusions"];
        put: operations["setCaseModelTaskModelExclusions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/task-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List task models */
        get: operations["listTaskModels"];
        put?: never;
        /** Create task model */
        post: operations["createTaskModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/task-models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTaskModel"];
        put?: never;
        post?: never;
        delete: operations["deleteTaskModel"];
        options?: never;
        head?: never;
        patch: operations["updateTaskModel"];
        trace?: never;
    };
    "/v1/task-models/{id}/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTaskModelAttributes"];
        put?: never;
        post: operations["createTaskModelAttribute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attribute-definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAttributeDefinition"];
        options?: never;
        head?: never;
        patch: operations["updateAttributeDefinition"];
        trace?: never;
    };
    "/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCases"];
        put?: never;
        post: operations["createCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCase"];
        put?: never;
        post?: never;
        delete: operations["deleteCase"];
        options?: never;
        head?: never;
        patch: operations["updateCase"];
        trace?: never;
    };
    "/v1/cases/{caseId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCaseTasks"];
        put?: never;
        post: operations["createCaseTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTasks"];
        put?: never;
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        patch: operations["updateTask"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterTenantRequest: {
            /** @description Kanzleiname */
            firm_name: string;
            admin_username: string;
            /** Format: email */
            admin_email: string;
            /** Format: password */
            admin_password: string;
            /** @enum {string} */
            default_language: "de" | "en";
        };
        CurrentUserResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            username: string;
            /** Format: email */
            email?: string | null;
            /** @enum {string|null} */
            preferred_language?: "de" | "en" | null;
            roles: string[];
        };
        AuthSessionResponse: {
            user: components["schemas"]["CurrentUserResponse"];
        };
        ErrorResponse: {
            /** @description Machine-readable error code */
            error: string;
            /** @description Localized human-readable message */
            message: string;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        TenantProfile: {
            /** Format: uuid */
            tenant_id: string;
            firm_name: string;
            /** @enum {string} */
            default_language: "de" | "en";
            settings?: {
                [key: string]: unknown;
            };
        };
        UpdateTenantProfileRequest: {
            firm_name?: string;
            /** @enum {string} */
            default_language?: "de" | "en";
            settings?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        ColorTheme: "classic" | "modern" | "forest" | "midnight";
        PatchTenantUiPreferencesRequest: {
            color_theme: components["schemas"]["ColorTheme"];
        };
        UiPreferences: {
            /** @description Effective theme for the current user */
            color_theme: components["schemas"]["ColorTheme"];
            /** @description Tenant default theme */
            tenant_color_theme: components["schemas"]["ColorTheme"];
            /** @description User override; null means use tenant default */
            user_color_theme: components["schemas"]["ColorTheme"] | null;
            available_themes: components["schemas"]["ColorTheme"][];
        };
        PatchUserUiPreferencesRequest: {
            /** @description Set a theme override, or null to use the tenant default */
            color_theme?: components["schemas"]["ColorTheme"] | null;
        };
        /** @example case-model-designer */
        AppKey: string;
        /** @enum {string} */
        AppInstallationStatus: "active" | "inactive";
        /** @enum {string} */
        AppMenuCategory: "administration" | "work";
        AppInstallation: {
            app_key: components["schemas"]["AppKey"];
            name: string;
            version: string;
            status: components["schemas"]["AppInstallationStatus"];
            /** Format: date-time */
            installed_at: string;
            has_react_ui: boolean;
            menu_category: components["schemas"]["AppMenuCategory"];
            /** @description Primary React UI route for sidebar navigation */
            nav_path: string | null;
            /** @description Lucide icon name for sidebar navigation (e.g. LuBriefcaseBusiness) */
            nav_icon: string | null;
        };
        TenantAppCatalogEntry: {
            app_key: components["schemas"]["AppKey"];
            name: string;
            version: string;
            description: string;
            has_react_ui: boolean;
            menu_category: components["schemas"]["AppMenuCategory"];
            nav_path: string | null;
            nav_icon: string | null;
            /** @description Whether the app has an installation row for this tenant */
            installed: boolean;
            /** @description null when never installed for this tenant */
            status: components["schemas"]["AppInstallationStatus"] | null;
            /** Format: date-time */
            installed_at: string | null;
        };
        PatchTenantAppStatusRequest: {
            status: components["schemas"]["AppInstallationStatus"];
        };
        AppSettingFieldSchema: {
            /** @enum {string} */
            type: "string" | "boolean" | "number";
            default: unknown;
            allowedValues?: unknown[];
            tenantConfigurable: boolean;
            userOverridable: boolean;
        };
        AppManifest: {
            app_key: components["schemas"]["AppKey"];
            name: string;
            version: string;
            description: string;
            has_react_ui: boolean;
            menu_category: components["schemas"]["AppMenuCategory"];
            /** @description Primary sidebar route when has_react_ui is true */
            nav_path: string;
            /** @description Lucide icon name for sidebar navigation (e.g. LuBriefcaseBusiness) */
            nav_icon: string;
            routes: {
                path: string;
                label: string;
            }[];
            required_roles: string[];
            settings_schema: {
                [key: string]: components["schemas"]["AppSettingFieldSchema"];
            };
            supported_locales: ("de" | "en")[];
            event_subscriptions?: string[];
        };
        AppSettings: {
            [key: string]: unknown;
        };
        EffectiveAppSettings: {
            app_key: components["schemas"]["AppKey"];
            settings: components["schemas"]["AppSettings"];
        };
        /** @description Partial settings object; only allowed keys are accepted */
        PatchAppSettingsRequest: {
            [key: string]: unknown;
        };
        Team: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateTeamRequest: {
            name: string;
        };
        UpdateTeamRequest: {
            name: string;
        };
        /**
         * @description Administrator or regular user
         * @enum {string}
         */
        TenantRoleKey: "admin" | "regular";
        TenantUser: {
            /** Format: uuid */
            id: string;
            username: string;
            /** Format: email */
            email?: string | null;
            role: components["schemas"]["TenantRoleKey"];
            /** Format: uuid */
            team_id?: string | null;
            team_name?: string | null;
            is_active: boolean;
            /** @enum {string|null} */
            preferred_language?: "de" | "en" | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateTenantUserRequest: {
            username: string;
            /** Format: email */
            email?: string | null;
            /** Format: password */
            password: string;
            role: components["schemas"]["TenantRoleKey"];
            /** Format: uuid */
            team_id?: string | null;
            /** @enum {string} */
            preferred_language?: "de" | "en";
        };
        UpdateTenantUserRequest: {
            /** Format: email */
            email?: string | null;
            /** Format: password */
            password?: string;
            role?: components["schemas"]["TenantRoleKey"];
            /** Format: uuid */
            team_id?: string | null;
            is_active?: boolean;
            /** @enum {string} */
            preferred_language?: "de" | "en";
        };
        ModelKey: string;
        /** @enum {string} */
        CaseModelStatus: "draft" | "active" | "archived";
        /**
         * @example {
         *       "de": "Fallakte",
         *       "en": "Case file"
         *     }
         */
        Translations: {
            [key: string]: string;
        };
        CaseModel: {
            /** Format: uuid */
            id: string;
            key: components["schemas"]["ModelKey"];
            status: components["schemas"]["CaseModelStatus"];
            translations: components["schemas"]["Translations"];
            /** @description Stable model description (plain text) */
            description: string;
            /** @deprecated */
            description_translations?: components["schemas"]["Translations"];
            /** @description Resolved label for the effective request locale (Accept-Language), with fallback de → en → key */
            display_name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Provide either name (server generates key and translations[locale]) or legacy key + translations. */
        CreateCaseModelRequest: {
            /** @description Display name in the given locale; server generates a unique key */
            name?: string;
            /**
             * @description Locale of name; defaults to Accept-Language when omitted
             * @enum {string}
             */
            locale?: "de" | "en";
            key?: components["schemas"]["ModelKey"];
            status?: components["schemas"]["CaseModelStatus"];
            translations?: components["schemas"]["Translations"];
            description?: string;
            /** @deprecated */
            description_translations?: components["schemas"]["Translations"];
        };
        UpdateCaseModelRequest: {
            /** @description Updates translations[locale] without removing other locales */
            name?: string;
            /**
             * @description Locale of name; defaults to Accept-Language when omitted
             * @enum {string}
             */
            locale?: "de" | "en";
            status?: components["schemas"]["CaseModelStatus"];
            translations?: components["schemas"]["Translations"];
            description?: string;
            /** @deprecated */
            description_translations?: components["schemas"]["Translations"];
        };
        /** @enum {string} */
        DefinitionScope: "model" | "instance";
        /** @enum {string} */
        DataType: "text" | "number" | "money" | "date" | "boolean" | "single_select" | "multi_select";
        /** @enum {string} */
        EncryptionMode: "server_readable" | "zero_knowledge";
        AttributeDefinition: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            owner_type: "case_model" | "task_model";
            /** Format: uuid */
            owner_id: string;
            definition_scope: components["schemas"]["DefinitionScope"];
            key: components["schemas"]["ModelKey"];
            data_type: components["schemas"]["DataType"];
            encryption_mode: components["schemas"]["EncryptionMode"];
            translations: components["schemas"]["Translations"];
            is_required: boolean;
            select_options: string[];
            /** @description Map of option key to locale labels (e.g. {"waiting_client":{"de":"…","en":"…"}}) */
            select_option_translations: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** @description Resolved option labels for the effective request locale (read-only in responses) */
            select_option_labels?: {
                [key: string]: string;
            };
            /** @description Default for new instances (instance scope) or model value (model scope) */
            default_value?: unknown;
            /** @description Resolved label for the effective request locale (Accept-Language), with fallback de → en → key */
            display_name: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /** @description Provide either name (server generates key and translations[locale]) or legacy key + translations. */
        CreateAttributeDefinitionRequest: {
            name?: string;
            /** @enum {string} */
            locale?: "de" | "en";
            definition_scope?: components["schemas"]["DefinitionScope"];
            key?: components["schemas"]["ModelKey"];
            data_type: components["schemas"]["DataType"];
            encryption_mode?: components["schemas"]["EncryptionMode"];
            translations?: components["schemas"]["Translations"];
            is_required?: boolean;
            select_options?: string[];
            select_option_translations?: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            default_value?: unknown;
        };
        CaseModelTaskModelExclusions: {
            /** @description Task models excluded from this case model (opt-out; all others allowed) */
            task_model_ids: string[];
        };
        TaskModel: {
            /** Format: uuid */
            id: string;
            key: components["schemas"]["ModelKey"];
            status: components["schemas"]["CaseModelStatus"];
            translations: components["schemas"]["Translations"];
            description: string;
            /** @deprecated */
            description_translations?: components["schemas"]["Translations"];
            display_name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Provide either name (server generates key and translations[locale]) or legacy key + translations. */
        CreateTaskModelRequest: {
            name?: string;
            /** @enum {string} */
            locale?: "de" | "en";
            key?: components["schemas"]["ModelKey"];
            status?: components["schemas"]["CaseModelStatus"];
            translations?: components["schemas"]["Translations"];
            description?: string;
        };
        UpdateTaskModelRequest: {
            name?: string;
            /** @enum {string} */
            locale?: "de" | "en";
            status?: components["schemas"]["CaseModelStatus"];
            translations?: components["schemas"]["Translations"];
            description?: string;
        };
        UpdateAttributeDefinitionRequest: {
            name?: string;
            /** @enum {string} */
            locale?: "de" | "en";
            data_type?: components["schemas"]["DataType"];
            encryption_mode?: components["schemas"]["EncryptionMode"];
            translations?: components["schemas"]["Translations"];
            is_required?: boolean;
            select_options?: string[];
            select_option_translations?: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            default_value?: unknown;
        };
        /** @description Language-neutral status key (e.g. active, open, closed) */
        StatusKey: string;
        Assignee: {
            /** Format: uuid */
            user_id: string;
            username: string;
        };
        Case: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            case_model_id: string;
            status: components["schemas"]["StatusKey"];
            encryption_status: string;
            encryption_version?: number | null;
            /** @description Attribute values keyed by definition key (includes status) */
            attributes?: {
                [key: string]: unknown;
            };
            assignees: components["schemas"]["Assignee"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateCaseRequest: {
            /** Format: uuid */
            case_model_id: string;
            status?: components["schemas"]["StatusKey"];
            attributes?: {
                [key: string]: unknown;
            };
            assignee_user_ids?: string[];
        };
        UpdateCaseRequest: {
            status?: components["schemas"]["StatusKey"];
            attributes?: {
                [key: string]: unknown;
            };
            assignee_user_ids?: string[];
        };
        Task: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            case_id: string;
            /** Format: uuid */
            task_model_id: string;
            status: components["schemas"]["StatusKey"];
            predecessor_task_ids: string[];
            dependent_task_ids: string[];
            encryption_status: string;
            encryption_version?: number | null;
            /** @description Attribute values keyed by definition key (includes status, title, task references) */
            attributes?: {
                [key: string]: unknown;
            };
            assignees: components["schemas"]["Assignee"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateCaseTaskRequest: {
            /** Format: uuid */
            task_model_id: string;
            status?: components["schemas"]["StatusKey"];
            predecessor_task_ids?: string[];
            dependent_task_ids?: string[];
            attributes?: {
                [key: string]: unknown;
            };
            assignee_user_ids?: string[];
        };
        CreateTaskRequest: {
            /** Format: uuid */
            case_id: string;
            /** Format: uuid */
            task_model_id: string;
            status?: components["schemas"]["StatusKey"];
            predecessor_task_ids?: string[];
            dependent_task_ids?: string[];
            attributes?: {
                [key: string]: unknown;
            };
            assignee_user_ids?: string[];
        };
        UpdateTaskRequest: {
            status?: components["schemas"]["StatusKey"];
            predecessor_task_ids?: string[];
            dependent_task_ids?: string[];
            attributes?: {
                [key: string]: unknown;
            };
            assignee_user_ids?: string[];
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource conflict (e.g. tenant slug already exists) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required or invalid */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        IdPath: string;
        AcceptLanguage: string;
        LangQuery: "de" | "en";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterTenantRequest"];
            };
        };
        responses: {
            /** @description Tenant and admin user created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getTenantProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateTenantProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantProfileRequest"];
            };
        };
        responses: {
            /** @description Updated profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantProfile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    patchTenantUiPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchTenantUiPreferencesRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UiPreferences"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getUiPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UiPreferences"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    patchUserUiPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchUserUiPreferencesRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UiPreferences"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listInstalledApps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AppInstallation"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTenantAppCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["TenantAppCatalogEntry"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    patchTenantAppStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appKey: components["schemas"]["AppKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchTenantAppStatusRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantAppCatalogEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getAppManifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appKey: components["schemas"]["AppKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppManifest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getEffectiveAppSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appKey: components["schemas"]["AppKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectiveAppSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getTenantAppSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appKey: components["schemas"]["AppKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    patchTenantAppSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appKey: components["schemas"]["AppKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchAppSettingsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getUserAppSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appKey: components["schemas"]["AppKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    patchUserAppSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appKey: components["schemas"]["AppKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchAppSettingsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Team"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listTenantUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["TenantUser"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createTenantUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantUserRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getTenantUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTenantUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listCaseModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["CaseModel"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCaseModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaseModelRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseModel"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    getCaseModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseModel"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteCaseModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateCaseModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCaseModelRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseModel"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listCaseModelAttributes: {
        parameters: {
            query?: {
                definition_scope?: components["schemas"]["DefinitionScope"];
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AttributeDefinition"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createCaseModelAttribute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAttributeDefinitionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeDefinition"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listCaseModelTaskModelExclusions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseModelTaskModelExclusions"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    setCaseModelTaskModelExclusions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseModelTaskModelExclusions"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseModelTaskModelExclusions"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTaskModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["TaskModel"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTaskModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskModelRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskModel"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    getTaskModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskModel"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTaskModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateTaskModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskModelRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskModel"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTaskModelAttributes: {
        parameters: {
            query?: {
                definition_scope?: components["schemas"]["DefinitionScope"];
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AttributeDefinition"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createTaskModelAttribute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAttributeDefinitionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeDefinition"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteAttributeDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateAttributeDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAttributeDefinitionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeDefinition"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listCases: {
        parameters: {
            query?: {
                case_model_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Case"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaseRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCaseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listCaseTasks: {
        parameters: {
            query?: {
                task_model_id?: string;
            };
            header?: never;
            path: {
                caseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Task"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createCaseTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaseTaskRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTasks: {
        parameters: {
            query?: {
                case_id?: string;
                task_model_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Task"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
